modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/someElseIsHere/Biomechanics/issues"
license = "MIT"

[[mods]]
modId = "cyberware"
version = "${version}"
displayName = "Cyberware"
authors = ["Flaxbeard", "An-Sar", "mallrat208", "LemADEC", "thePlaceholder"]
description = '''
Augmentation in Minecraft
'''
logoFile = "assets/cyberware/icon.png"

[[dependencies.cyberware]]
modId = "neoforge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cyberware]]
modId = "minecraft"
mandatory = true
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cyberware]]
modId = "architectury"
mandatory = true
versionRange = "[12.1.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
